Realizando fallos intencionales

diff --git a/.github/workflows/cypress-test.yml b/.github/workflows/cypress-test.yml
--- a/.github/workflows/cypress-test.yml
+++ b/.github/workflows/cypress-test.yml
@@ -30,18 +30,20 @@ jobs:
         run: npm run limpiar-reporte
 
       - name: Run Cypress Tests with Allure Adapter
-        run: npm run ejecutar-pruebas
-
-      - name: List Allure Results
-        run: ls -la ./allure-results  # Verifica que hay archivos generados en allure-results
+        run: npm run ejecutar-pruebas || echo "Cypress tests failed but continuing"
 
       - name: Ensure Allure Report Directory Exists
         run: mkdir -p ./allure-report
 
-      - name: Generate Allure Report as Static HTML
-        run: allure generate ./allure-results --clean -o ./allure-report || echo "Allure report generation failed"
+      - name: Check for Allure Results and Generate Report if Available
+        run: |
+          if [ -d "./allure-results" ] && [ "$(ls -A ./allure-results)" ]; then
+            allure generate ./allure-results --clean -o ./allure-report
+          else
+            echo "No allure results found, skipping report generation."
+          fi
 
-      # Este paso siempre se ejecutará, incluso si los pasos anteriores fallan
+      # Subir el artefacto incluso si las pruebas fallan
       - name: Upload Allure Report
         if: always()
         uses: actions/upload-artifact@v3
