Realizando fallos intencionales

diff --git a/.github/workflows/cypress-test.yml b/.github/workflows/cypress-test.yml
--- a/.github/workflows/cypress-test.yml
+++ b/.github/workflows/cypress-test.yml
@@ -16,7 +16,7 @@ jobs:
       - name: Setup Node.js
         uses: actions/setup-node@v3
         with:
-          node-version: '21.7.3'
+          node-version: '20.x'
 
       - name: Install dependencies
         run: npm install
@@ -33,11 +33,15 @@ jobs:
         run: npm run ejecutar-pruebas
 
       - name: List Allure Results
-        run: ls -la ./allure-results
+        run: ls -la ./allure-results  # Verifica que hay archivos generados en allure-results
+
+      - name: Ensure Allure Report Directory Exists
+        run: mkdir -p ./allure-report
 
       - name: Generate Allure Report as Static HTML
-        run: allure generate ./allure-results --clean -o ./allure-report
+        run: allure generate ./allure-results --clean -o ./allure-report || echo "Allure report generation failed"
 
+      # Este paso siempre se ejecutará, incluso si los pasos anteriores fallan
       - name: Upload Allure Report
         if: always()
         uses: actions/upload-artifact@v3
